const ErrorCodes = {
    USER_NOT_FOUND: "USER_NOT_FOUND",
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
    INVALID_STATUS: "INVALID_STATUS",
    INVALID_QUANTITY: "INVALID_QUANTITY",
    DATABASE_ERROR: "DATABASE_ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR"
};

export default ErrorCodes;